name: covidanalysis
version: 0.5
description: This package provides source code from the stockquotes example which accompany the book"Haskell in Depth" by Vitaly Bragilevsky (Manning Publications 2020).

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.

dependencies:
- base >= 4.7 && < 5
- text
- fmt
- cassava
- bytestring
- time
- blaze-html
- blaze-colonnade
- colonnade
- vector

library:
  source-dirs: src

executables:
  covidanalysis-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - covidanalysis

tests:
  stockquotes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - covidanalysis
